// User Types
export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP_USER = "SIGNUP_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";

// Error Types
export const SET_TOAST = "SET_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";

// Rooms Types
export const SYNC_ROOMS = "SYNC_ROOMS";
export const SYNC_ROOMS_SUCCESS = "SYNC_ROOMS_SUCCESS";
export const SYNC_ROOMS_FAIL = "SYNC_ROOMS_FAIL";
export const SET_ROOMS = "SET_ROOMS";
export const ADD_NEW_ROOM = "ADD_NEW_ROOM";

export const DELETE_ROOM_START = "DELETE_ROOM_START";
export const DELETE_ROOM = "DELETE_ROOM";

export const SYNC_MESSAGES = "SYNC_MESSAGES";
export const SYNC_MESSAGES_SUCCESS = "SYNC_MESSAGES_SUCCESS";
export const SYNC_MESSAGES_FAIL = "SYNC_MESSAGES_FAIL";
export const SET_MESSAGES = "SET_MESSAGES";
export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";

export const SET_ROOMS_LOADING = "SET_ROOMS_LOADING";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";
